services:

  mysqldb-specieslist:
    image: mysql:8.4
    volumes:
      - db_data_specieslists:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: specieslists
      MYSQL_USER: specieslists
      MYSQL_PASSWORD: specieslists
    ports:
      - 3306:3306

  specieslist:
    image: sbdi/specieslist-webapp-dev
    build:
      context: .
      no_cache: true
    ports:
      - 8080:8080
    volumes:
      - ./sbdi/data/config/specieslist-webapp-config.properties:/data/specieslist-webapp/config/specieslist-webapp-config.properties
volumes:
  db_data_specieslists:
